// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa82km4NuAUUxGB8b0TsUm7ttoHdoLU_4',
    appId: '1:1057950452705:web:d74752345a1c98848aa0a0',
    messagingSenderId: '1057950452705',
    projectId: 'bookswap-ca2e5',
    authDomain: 'bookswap-ca2e5.firebaseapp.com',
    storageBucket: 'bookswap-ca2e5.firebasestorage.app',
    measurementId: 'G-9MJ8MSC0RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_abJy-geIZhsHZdfU351MoqNgV78ElPo',
    appId: '1:1057950452705:android:f06b0df416aaa93a8aa0a0',
    messagingSenderId: '1057950452705',
    projectId: 'bookswap-ca2e5',
    storageBucket: 'bookswap-ca2e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgynlHEYTJroXAK2qHLpIlY5RLeeruyFM',
    appId: '1:1057950452705:ios:2e1856225496733e8aa0a0',
    messagingSenderId: '1057950452705',
    projectId: 'bookswap-ca2e5',
    storageBucket: 'bookswap-ca2e5.firebasestorage.app',
    iosBundleId: 'com.example.bookSwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgynlHEYTJroXAK2qHLpIlY5RLeeruyFM',
    appId: '1:1057950452705:ios:2e1856225496733e8aa0a0',
    messagingSenderId: '1057950452705',
    projectId: 'bookswap-ca2e5',
    storageBucket: 'bookswap-ca2e5.firebasestorage.app',
    iosBundleId: 'com.example.bookSwap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa82km4NuAUUxGB8b0TsUm7ttoHdoLU_4',
    appId: '1:1057950452705:web:24da5a069970caaa8aa0a0',
    messagingSenderId: '1057950452705',
    projectId: 'bookswap-ca2e5',
    authDomain: 'bookswap-ca2e5.firebaseapp.com',
    storageBucket: 'bookswap-ca2e5.firebasestorage.app',
    measurementId: 'G-E5PRQQ4LXV',
  );
}
